// Code generated by gamedata. DO NOT EDIT
package gamedata

/*{
	"Fields": [
		{
			"Name": "Title",
			"Type": "string"
		},
		{
			"Name": "Description",
			"Type": "string"
		},
		{
			"Name": "developer",
			"Type": "*game.Game_Developer"
		},
		{
			"Name": "category",
			"Type": "game.Game_Category"
		},
		{
			"Name": "role_playing_extra",
			"Type": "*game.Game_RolePlayingExtra"
		},
		{
			"Name": "shooting_extra",
			"Type": "*game.Game_ShootingExtra"
		}
	],
	"CatToExtra": {
		"ROLE_PLAYING": {
			"Name": "role_playing_extra",
			"Fields": [
				{
					"Name": "number_of_bosses",
					"Type": "int32"
				}
			]
		},
		"SHOOTING": {
			"Name": "shooting_extra",
			"Fields": [
				{
					"Name": "number_of_guns",
					"Type": "int32"
				}
			]
		}
	}
}*/
