// syntax = "proto3";

// package game;

// import "google/protobuf/descriptor.proto";
// import "google/protobuf/empty.proto";
// import "google/protobuf/timestamp.proto";
// import "google/protobuf/duration.proto";
// import "google/protobuf/struct.proto";
// import "google/protobuf/any.proto";

// message Something {
//   google.protobuf.Struct s = 1;
//   google.protobuf.Duration a = 2;
// }

// option go_package = "github.com/HomayoonAlimohammadi/protoc-gen-gamedata/proto/game";

// service GameShop {
//     rpc GetGame(google.protobuf.Empty) returns (RegisterGameResponse);
// }

// message Version {
//   int32 minor = 1;
//   int32 major = 2;
// }
// extend google.protobuf.FieldOptions {
//   bool should_use = 1000;
//   Version version = 1001;
// }

// extend google.protobuf.EnumValueOptions {
//   bool is_valid_category = 1000;
// }

// extend google.protobuf.EnumOptions {
//   string description = 1000;
// }

// extend google.protobuf.OneofOptions {
//   repeated string respective_categories = 1000;
// }

// message Game {
//   string title = 1 [(version) = {minor: 10, major: 1}];
//             // or: [(version).major = 10, (version).minor = 1]
//   google.protobuf.Timestamp release_date = 2 [json_name = "releaseDate"];
//   enum Category {
//     option (description) = "this defines the game category";
//     UNKNOWN = 0 [(is_valid_category) = false];
//     SHOOTING = 1; // a game like call of duty
//     STRATEGY = 2;
//   }
//   Category category = 3;

//   message ShootingExtra {
//     optional int32 number_of_guns = 1;
//   }

//   message StrategyExtra {
//     optional bool is_medieval = 1;
//   }

//   message UnknownExtra {}

//   oneof extra {
//     option (respective_categories) = "SHOOTING";
//     option (respective_categories) = "STRATEGY";
//     UnknownExtra unknown_extra = 4 [(should_use) = false];
//     ShootingExtra shooting_extra = 5;
//     StrategyExtra strategy_extra = 6;
//   }

//   string developer_name = 7 [deprecated = true];
// }

// message RegisterGameResponse {
//     bool ok = 1;
// }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game_Category int32

const (
	Game_UNKNOWN      Game_Category = 0
	Game_ROLE_PLAYING Game_Category = 1
	Game_SHOOTING     Game_Category = 2
)

// Enum value maps for Game_Category.
var (
	Game_Category_name = map[int32]string{
		0: "UNKNOWN",
		1: "ROLE_PLAYING",
		2: "SHOOTING",
	}
	Game_Category_value = map[string]int32{
		"UNKNOWN":      0,
		"ROLE_PLAYING": 1,
		"SHOOTING":     2,
	}
)

func (x Game_Category) Enum() *Game_Category {
	p := new(Game_Category)
	*p = x
	return p
}

func (x Game_Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_Category) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_game_proto_enumTypes[0].Descriptor()
}

func (Game_Category) Type() protoreflect.EnumType {
	return &file_proto_game_game_proto_enumTypes[0]
}

func (x Game_Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_Category.Descriptor instead.
func (Game_Category) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0, 0}
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string          `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string          `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Developer   *Game_Developer `protobuf:"bytes,3,opt,name=developer,proto3" json:"developer,omitempty"`
	Category    Game_Category   `protobuf:"varint,4,opt,name=category,proto3,enum=game.Game_Category" json:"category,omitempty"`
	// Types that are assignable to Extra:
	//
	//	*Game_RolePlayingExtra_
	//	*Game_ShootingExtra_
	Extra isGame_Extra `protobuf_oneof:"extra"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetDeveloper() *Game_Developer {
	if x != nil {
		return x.Developer
	}
	return nil
}

func (x *Game) GetCategory() Game_Category {
	if x != nil {
		return x.Category
	}
	return Game_UNKNOWN
}

func (m *Game) GetExtra() isGame_Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (x *Game) GetRolePlayingExtra() *Game_RolePlayingExtra {
	if x, ok := x.GetExtra().(*Game_RolePlayingExtra_); ok {
		return x.RolePlayingExtra
	}
	return nil
}

func (x *Game) GetShootingExtra() *Game_ShootingExtra {
	if x, ok := x.GetExtra().(*Game_ShootingExtra_); ok {
		return x.ShootingExtra
	}
	return nil
}

type isGame_Extra interface {
	isGame_Extra()
}

type Game_RolePlayingExtra_ struct {
	RolePlayingExtra *Game_RolePlayingExtra `protobuf:"bytes,5,opt,name=role_playing_extra,json=rolePlayingExtra,proto3,oneof"`
}

type Game_ShootingExtra_ struct {
	ShootingExtra *Game_ShootingExtra `protobuf:"bytes,6,opt,name=shooting_extra,json=shootingExtra,proto3,oneof"`
}

func (*Game_RolePlayingExtra_) isGame_Extra() {}

func (*Game_ShootingExtra_) isGame_Extra() {}

type Game_Developer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Game_Developer) Reset() {
	*x = Game_Developer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game_Developer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_Developer) ProtoMessage() {}

func (x *Game_Developer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_Developer.ProtoReflect.Descriptor instead.
func (*Game_Developer) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Game_Developer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Game_RolePlayingExtra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfBosses int32 `protobuf:"varint,1,opt,name=number_of_bosses,json=numberOfBosses,proto3" json:"number_of_bosses,omitempty"`
}

func (x *Game_RolePlayingExtra) Reset() {
	*x = Game_RolePlayingExtra{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game_RolePlayingExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_RolePlayingExtra) ProtoMessage() {}

func (x *Game_RolePlayingExtra) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_RolePlayingExtra.ProtoReflect.Descriptor instead.
func (*Game_RolePlayingExtra) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Game_RolePlayingExtra) GetNumberOfBosses() int32 {
	if x != nil {
		return x.NumberOfBosses
	}
	return 0
}

type Game_ShootingExtra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfGuns int32 `protobuf:"varint,2,opt,name=number_of_guns,json=numberOfGuns,proto3" json:"number_of_guns,omitempty"`
}

func (x *Game_ShootingExtra) Reset() {
	*x = Game_ShootingExtra{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game_ShootingExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_ShootingExtra) ProtoMessage() {}

func (x *Game_ShootingExtra) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_ShootingExtra.ProtoReflect.Descriptor instead.
func (*Game_ShootingExtra) Descriptor() ([]byte, []int) {
	return file_proto_game_game_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Game_ShootingExtra) GetNumberOfGuns() int32 {
	if x != nil {
		return x.NumberOfGuns
	}
	return 0
}

var File_proto_game_game_proto protoreflect.FileDescriptor

var file_proto_game_game_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x04,
	0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32,
	0x0a, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x44, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x52, 0x09, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x4b, 0x0a, 0x12, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x69, 0x6e, 0x67, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x74, 0x72, 0x61, 0x48, 0x00, 0x52, 0x10,
	0x72, 0x6f, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x12, 0x41, 0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x1a, 0x1f, 0x0a, 0x09, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x3c, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x69, 0x6e, 0x67, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x6f, 0x73, 0x73,
	0x65, 0x73, 0x1a, 0x35, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66,
	0x5f, 0x67, 0x75, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x47, 0x75, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x08, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x48, 0x4f, 0x4f, 0x54, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x40, 0x5a, 0x3e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x6d, 0x61, 0x79, 0x6f,
	0x6f, 0x6e, 0x41, 0x6c, 0x69, 0x6d, 0x6f, 0x68, 0x61, 0x6d, 0x6d, 0x61, 0x64, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_game_proto_rawDescOnce sync.Once
	file_proto_game_game_proto_rawDescData = file_proto_game_game_proto_rawDesc
)

func file_proto_game_game_proto_rawDescGZIP() []byte {
	file_proto_game_game_proto_rawDescOnce.Do(func() {
		file_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_game_proto_rawDescData)
	})
	return file_proto_game_game_proto_rawDescData
}

var file_proto_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_game_game_proto_goTypes = []interface{}{
	(Game_Category)(0),            // 0: game.Game.Category
	(*Game)(nil),                  // 1: game.Game
	(*Game_Developer)(nil),        // 2: game.Game.Developer
	(*Game_RolePlayingExtra)(nil), // 3: game.Game.RolePlayingExtra
	(*Game_ShootingExtra)(nil),    // 4: game.Game.ShootingExtra
}
var file_proto_game_game_proto_depIdxs = []int32{
	2, // 0: game.Game.developer:type_name -> game.Game.Developer
	0, // 1: game.Game.category:type_name -> game.Game.Category
	3, // 2: game.Game.role_playing_extra:type_name -> game.Game.RolePlayingExtra
	4, // 3: game.Game.shooting_extra:type_name -> game.Game.ShootingExtra
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_game_game_proto_init() }
func file_proto_game_game_proto_init() {
	if File_proto_game_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_game_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game_Developer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game_RolePlayingExtra); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game_ShootingExtra); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_game_game_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Game_RolePlayingExtra_)(nil),
		(*Game_ShootingExtra_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_game_proto_goTypes,
		DependencyIndexes: file_proto_game_game_proto_depIdxs,
		EnumInfos:         file_proto_game_game_proto_enumTypes,
		MessageInfos:      file_proto_game_game_proto_msgTypes,
	}.Build()
	File_proto_game_game_proto = out.File
	file_proto_game_game_proto_rawDesc = nil
	file_proto_game_game_proto_goTypes = nil
	file_proto_game_game_proto_depIdxs = nil
}
